site_name: BFC Production Support
site_url: https://bfcproduction.github.io/bfc-production-support
theme:
  name: material
  logo: assets/bfc-logo.png
  favicon: assets/bfc-logo.png
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
extra_css:
  - assets/custom.css
plugins:
  - search
  - glightbox
repo_url: https://github.com/BFCProduction/bfc-production-support
repo_name: BFCProduction/bfc-production-support