site_name: BFC Production Support
site_url: https://bfcproduction.github.io/bfc-production-support
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
plugins:
  - search
  - glightbox
nav:
  - Home: index.md
  - Audio: audio/index.md
  - Video: video/index.md
  - Lighting:
    - Overview: lighting/index.md
    - Connecting MA3 to Arena: lighting/connecting-ma3-to-arena.md
  - Network: network/index.md
  - Workflows:
    - Overview: workflows/index.md
    - BFC Kiosk - Using Info Beamer: workflows/tv-kiosks-bfc-hd-info-beamer.md
    - Creating a New Support Page: workflows/creating-a-new-support-page.md
repo_url: https://github.com/BFCProduction/bfc-production-support
repo_name: BFCProduction/bfc-production-support